# Generated by Django 3.2.7 on 2021-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthPlace',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodType',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='eps',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='expeditionOfDocumentDepartment',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='expeditionOfDocumentPlace',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
