# Generated by Django 3.2.7 on 2021-09-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210925_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semesterName',
            field=models.CharField(max_length=7),
        ),
    ]
