# Generated by Django 3.2.7 on 2021-09-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_parent_typeofdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
