# Generated by Django 3.2.7 on 2021-09-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_semester_semestername'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
